// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package org.hzz.grpc;

public interface RPCDateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.hzz.protobuf.RPCDateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string userName = 1;</code>
   * @return The userName.
   */
  String getUserName();
  /**
   * <code>string userName = 1;</code>
   * @return The bytes for userName.
   */
  com.google.protobuf.ByteString
      getUserNameBytes();
}
