// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: helloworld.proto

package org.hzz.grpc;

public final class RPCDateServiceApi {
  private RPCDateServiceApi() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_hzz_protobuf_RPCDateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_hzz_protobuf_RPCDateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_hzz_protobuf_RPCDateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_hzz_protobuf_RPCDateResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020helloworld.proto\022\020org.hzz.protobuf\"\"\n\016" +
      "RPCDateRequest\022\020\n\010userName\030\001 \001(\t\"%\n\017RPCD" +
      "ateResponse\022\022\n\nserverDate\030\001 \001(\t2b\n\016RPCDa" +
      "teService\022P\n\007getDate\022 .org.hzz.protobuf." +
      "RPCDateRequest\032!.org.hzz.protobuf.RPCDat" +
      "eResponse\"\000B#\n\014org.hzz.grpcB\021RPCDateServ" +
      "iceApiP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_hzz_protobuf_RPCDateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_hzz_protobuf_RPCDateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_hzz_protobuf_RPCDateRequest_descriptor,
        new String[] { "UserName", });
    internal_static_org_hzz_protobuf_RPCDateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_hzz_protobuf_RPCDateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_hzz_protobuf_RPCDateResponse_descriptor,
        new String[] { "ServerDate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
